version: "3"

services:
    wordpress:
        image: wordpress:5-php7.3
        ports:
            - "80:80"
        volumes:
            - "./.docker-cache/uploads/:/var/www/html/wp-content/uploads/"
            - "./.docker-cache/plugins/:/var/www/html/wp-content/plugins/"
            - "./:/var/www/html/wp-content/themes/wordpress-boilerplate/"
        depends_on: 
            - db
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: root
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DEBUG: 1
    db:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress